// Generated by make generate-test-cases

import Testing
@testable import SVGView

struct SVGCustomTests: SVGTestHelper {

    var dir: String {
        "Custom"
    }

    @Test func graph01() async throws {
        // Baseline parsing snapshot for a large graph-like SVG fixture.
        try await compareToReference("graph-01")
    }

    @Test func viewport01() async throws {
        // Verifies viewport handling for the first custom viewport fixture.
        try await compareToReference("viewport-01")
    }

    @Test func viewport02() async throws {
        // Verifies viewport handling for the second custom viewport fixture.
        try await compareToReference("viewport-02")
    }

    @Test func scriptGating01() async throws {
        // Unsupported script MIME type must be ignored, so the square stays blue.
        try await compareToReference("script-gating-01")
    }

    @Test func scriptGating02() async throws {
        // Unsupported root contentScriptType should prevent untyped script execution.
        try await compareToReference("script-gating-02")
    }

    @Test func scriptGating03() async throws {
        // Supported script MIME type should execute and turn the square red.
        try await compareToReference("script-gating-03")
    }

    @Test func scriptGating04() async throws {
        // Untyped script should execute with default script MIME handling.
        try await compareToReference("script-gating-04")
    }

    @Test func scriptStroke01() async throws {
        // Unsupported script MIME type must not mutate stroke properties.
        try await compareToReference("script-stroke-01")
    }

    @Test func scriptStroke02() async throws {
        // Supported script MIME type should mutate stroke color/width/opacity.
        try await compareToReference("script-stroke-02")
    }

    @Test func scriptStroke03() async throws {
        // Unsupported script MIME type must not mutate stroke dash properties.
        try await compareToReference("script-stroke-03")
    }

    @Test func scriptStroke04() async throws {
        // Supported script MIME type should mutate stroke dasharray/dashoffset.
        try await compareToReference("script-stroke-04")
    }

    @Test func scriptStroke05() async throws {
        // Unsupported script MIME type must not mutate cap/join/miterlimit.
        try await compareToReference("script-stroke-05")
    }

    @Test func scriptStroke06() async throws {
        // Supported script MIME type should mutate cap/join/miterlimit.
        try await compareToReference("script-stroke-06")
    }

    @Test func scriptFillRule01() async throws {
        // Unsupported script MIME type must not mutate path fill-rule.
        try await compareToReference("script-fillrule-01")
    }

    @Test func scriptFillRule02() async throws {
        // Supported script MIME type should mutate path fill-rule.
        try await compareToReference("script-fillrule-02")
    }

    @Test func scriptCurrentColor01() async throws {
        // Unsupported script MIME type must not mutate fill via currentColor.
        try await compareToReference("script-currentcolor-01")
    }

    @Test func scriptCurrentColor02() async throws {
        // fill=currentColor then color=red should resolve to red.
        try await compareToReference("script-currentcolor-02")
    }

    @Test func scriptCurrentColor03() async throws {
        // color=lime then fill=currentColor should resolve to lime.
        try await compareToReference("script-currentcolor-03")
    }

}
